### ISSUE TITLE
关于 mask 的处理

### ISSUE THREAD

**Issue by onshek** [onshek/gplearn#1]
**Is your feature request related to a problem? Please describe.**

mask 应该可以省略

**Describe the solution you'd like**

虽然在实例化 `gplearn.genetic.SymbolicTransformer` 的时候就应该输入 `function_set`，但实际上在 `fit` 中，是这样使用的：
```
        self._function_set = []
        for function in self.function_set:
            if isinstance(function, str):
                if function not in _function_map:
                    raise ValueError('invalid function name %s found in '
                                     '`function_set`.' % function)
                self._function_set.append(_function_map[function])
            elif isinstance(function, _Function):
                self._function_set.append(function)
            else:
                raise ValueError('invalid type %s found in `function_set`.'
                                 % type(function))
```
也就是说，可以在这里重构 `function_set`，给有需要的 func 的形参 `mask` 一个实参，因为在这里，`X` 和 `y` 都拿到实参了（这里应该输入二维数据，来得到 `mask`）

**Additional context**

后剪枝依然需要，但只要判断每一个 func 有无形参 `d` 即可，无需新建两份自定义 func set；
关于缺失值，重新自定义 check_X_y 可以解决，如有必要，则通过 `make_fitness` 改写可适应缺失值的 protected fitness func
@otthqs

**Comment by otthqs** [comment]
### 1.
原文中的在fit中的function_set的使用，是将本身为str的参数对象，通过_function_map映射到了内置的函数上，即将输入的function_set = ["add", "sub"]在构造实例化的_Program内前，映射成function_set = [add, sub]，其中add和sub是_Function的实例化对象。

### 2.
在实例化gplearn.genetic.SymbolicTransformer时， 每一个feature是一个列向量，每一行是一个训练的sample无法直接传入二维数组。 make_fitness是可以重新定义改写。

**Comment by onshek** [comment]
第一部分，我的意思是，在 `fit` 前，重新 make func，并且传入二维的 `mask`
第二部分，虽然传入的每一个 feature 是二维的，但在拿到 `mask` 之后，再展成一维即可
经过上面两步，`mask` 应该可以封装起来

**Comment by otthqs** [comment]
明白了，应该可行！
